ci:
  autofix_prs: true
  autoupdate_schedule: weekly
  autofix_commit_msg: "fix(pre_commit): 🎨 auto format pre-commit hooks"
  autoupdate_commit_msg: "chore(pre_commit): ⬆ pre_commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-case-conflict
      - id: check-added-large-files
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: extract-pot
        name: Extract POT file
        entry: bash po/extract-pot.sh
        language: system
        files: ^(data/.*\\.js|src/i18nHelpers\\.js)$
        pass_filenames: false
        stages: [commit]
        # This hook modifies po/template.pot.
        # pre-commit will automatically stage changes to this file if the script modifies it.

  - repo: local
    hooks:
      - id: js-lint
        name: Lint JavaScript files
        entry: npm run lint
        language: node
        stages: [commit]
        additional_dependencies: [eslint, globals]

  - repo: local
    hooks:
      - id: js-prettier
        name: Format JavaScript files
        entry: npm run format
        language: node
        stages: [commit]
        additional_dependencies: [prettier]

  - repo: local
    hooks:
      - id: build-css
        name: Run CSS build
        entry: npm run build:css
        language: node
        stages: [commit]
        additional_dependencies: [less]
