[build]
  command = "npm run build:css"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["data/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
