[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["data/**", "views/**", "locales/**", "app.js"]
  external_node_modules = ["express", "ejs"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
