[build]
  command = "npm install && npm run build:css"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"
  included_files = ["data/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
