[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "zisi"
  included_files = ["data/**", "views/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
